
export enum AppView {
  DASHBOARD = 'DASHBOARD',
  TRANSACTIONS = 'TRANSACTIONS',
  SHU_DISTRIBUTION = 'SHU_DISTRIBUTION',
  DIGITAL_PASSBOOK = 'DIGITAL_PASSBOOK',
  LOAN_SIMULATOR = 'LOAN_SIMULATOR',
  VOUCHING_SYSTEM = 'VOUCHING_SYSTEM',
  LOAN_HISTORY = 'LOAN_HISTORY',
  LOAN_READINESS = 'LOAN_READINESS',
  AI_CREDIT_COMMITTEE = 'AI_CREDIT_COMMITTEE',
  MEMBER_MARKETPLACE = 'MEMBER_MARKETPLACE',
  MERCHANT_DASHBOARD = 'MERCHANT_DASHBOARD',
  ARISAN_DIGITAL = 'ARISAN_DIGITAL',
  ASSET_AUCTION = 'ASSET_AUCTION',
  WALLET_INTEGRATION = 'WALLET_INTEGRATION',
  SMART_PROCUREMENT = 'SMART_PROCUREMENT',
  BILL_PAYMENTS = 'BILL_PAYMENTS',
  MEMBER_QRIS = 'MEMBER_QRIS',
  MEMBER_HEALTH_SHIELD = 'MEMBER_HEALTH_SHIELD',
  PERSONAL_GOLD = 'PERSONAL_GOLD',
  PENSION_FUND = 'PENSION_FUND',
  DASKOP_CLAIM = 'DASKOP_CLAIM',
  SMART_EDUCATION = 'SMART_EDUCATION',
  AI_ADVISOR = 'AI_ADVISOR',
  MEMBERSHIP_PROFILE = 'MEMBERSHIP_PROFILE',
  MEMBERSHIP_CERTIFICATE = 'MEMBERSHIP_CERTIFICATE',
  GLOBAL_COMMAND_CENTER = 'GLOBAL_COMMAND_CENTER',
  STRATEGIC_PROFIT_CALCULATOR = 'STRATEGIC_PROFIT_CALCULATOR',
  ECOSYSTEM_REVENUE = 'ECOSYSTEM_REVENUE',
  DEPLOYMENT_HUB = 'DEPLOYMENT_HUB',
  SYSTEM_HEALTH = 'SYSTEM_HEALTH',
  ACCOUNTING = 'ACCOUNTING',
  REVENUE_CENTER = 'REVENUE_CENTER',
  REVENUE_CENTER_TAX = 'REVENUE_CENTER_TAX',
  CASH_WITHDRAWAL = 'CASH_WITHDRAWAL',
  SMART_MOBILITY = 'SMART_MOBILITY',
  NOTIFICATION_CENTER = 'NOTIFICATION_CENTER',
  MEMBER_INSTALLMENT_PAYMENT = 'MEMBER_INSTALLMENT_PAYMENT',
  DUTA_ECHOES = 'DUTA_ECHOES',
  DUTA_AWARDING = 'DUTA_AWARDING',
  MONETIZATION_IDEAS = 'MONETIZATION_IDEAS'
}

export enum UserRole {
  FOUNDER = 'FOUNDER',
  BOARD = 'BOARD',
  STAFF = 'STAFF',
  MEMBER = 'MEMBER',
  LEADER = 'LEADER',
  AUDITOR = 'AUDITOR',
  GOVERNMENT = 'GOVERNMENT'
}

export interface UserProfile {
  id: string;
  name: string;
  role: UserRole;
  memberId: string;
  balances: {
    principal: number;
    mandatory: number;
    voluntary: number;
  };
  reputationScore: number;
}

export interface ChatMessage {
  role: 'user' | 'model';
  text: string;
}

export interface Transaction {
  id: string;
  type: 'deposit' | 'withdrawal' | 'loan_installment' | 'dividend';
  description: string;
  date: string;
  amount: number;
  status: 'completed' | 'pending' | 'failed';
}
