
export const AppView = {
  DASHBOARD: 'DASHBOARD',
  TRANSACTIONS: 'TRANSACTIONS',
  SHU_DISTRIBUTION: 'SHU_DISTRIBUTION',
  ARISAN_DIGITAL: 'ARISAN_DIGITAL',
  MEMBER_MARKETPLACE: 'MEMBER_MARKETPLACE',
  MERCHANT_DASHBOARD: 'MERCHANT_DASHBOARD',
  BILL_PAYMENTS: 'BILL_PAYMENTS',
  DIGITAL_PASSBOOK: 'DIGITAL_PASSBOOK',
  SMART_EDUCATION: 'SMART_EDUCATION',
  MEMBERSHIP_PROFILE: 'MEMBERSHIP_PROFILE',
  AI_ADVISOR: 'AI_ADVISOR',
  LOAN_SIMULATOR: 'LOAN_SIMULATOR',
  LOAN_HISTORY: 'LOAN_HISTORY',
  DEPLOYMENT_HUB: 'DEPLOYMENT_HUB',
  VOUCHING_SYSTEM: 'VOUCHING_SYSTEM'
};

export const UserRole = {
  FOUNDER: 'FOUNDER',
  BOARD: 'BOARD',
  MEMBER: 'MEMBER',
};
