export enum AppView {
  DASHBOARD = 'DASHBOARD',
  TRANSACTIONS = 'TRANSACTIONS',
  SHU_DISTRIBUTION = 'SHU_DISTRIBUTION',
  DIGITAL_PASSBOOK = 'DIGITAL_PASSBOOK',
  LOAN_SIMULATOR = 'LOAN_SIMULATOR',
  VOUCHING_SYSTEM = 'VOUCHING_SYSTEM',
  LOAN_HISTORY = 'LOAN_HISTORY',
  LOAN_READINESS = 'LOAN_READINESS',
  AI_CREDIT_COMMITTEE = 'AI_CREDIT_COMMITTEE',
  MEMBER_MARKETPLACE = 'MEMBER_MARKETPLACE',
  MERCHANT_DASHBOARD = 'MERCHANT_DASHBOARD',
  ARISAN_DIGITAL = 'ARISAN_DIGITAL',
  SMART_PROCUREMENT = 'SMART_PROCUREMENT',
  BILL_PAYMENTS = 'BILL_PAYMENTS',
  MEMBER_QRIS = 'MEMBER_QRIS',
  MEMBER_HEALTH_SHIELD = 'MEMBER_HEALTH_SHIELD',
  PERSONAL_GOLD = 'PERSONAL_GOLD',
  PENSION_FUND = 'PENSION_FUND',
  DASKOP_CLAIM = 'DASKOP_CLAIM',
  SMART_EDUCATION = 'SMART_EDUCATION',
  AI_ADVISOR = 'AI_ADVISOR',
  MEMBERSHIP_PROFILE = 'MEMBERSHIP_PROFILE',
  MEMBERSHIP_CERTIFICATE = 'MEMBERSHIP_CERTIFICATE',
  GLOBAL_COMMAND_CENTER = 'GLOBAL_COMMAND_CENTER',
  STRATEGIC_PROFIT_CALCULATOR = 'STRATEGIC_PROFIT_CALCULATOR',
  ECOSYSTEM_REVENUE = 'ECOSYSTEM_REVENUE',
  DEPLOYMENT_HUB = 'DEPLOYMENT_HUB',
  SYSTEM_HEALTH = 'SYSTEM_HEALTH',
  ACCOUNTING = 'ACCOUNTING',
  REVENUE_CENTER = 'REVENUE_CENTER',
  CASH_WITHDRAWAL = 'CASH_WITHDRAWAL',
  SMART_MOBILITY = 'SMART_MOBILITY',
  DUTA_RECRUITMENT = 'DUTA_RECRUITMENT',
  TERRITORY_MAP = 'TERRITORY_MAP',
  TERRITORY_COMMAND = 'TERRITORY_COMMAND',
  DUTA_SOP = 'DUTA_SOP',
  MEMBER_ATTRACTION = 'MEMBER_ATTRACTION',
  PROMOTION_KIT = 'PROMOTION_KIT',
  OFFICIAL_ASSIGNMENT = 'OFFICIAL_ASSIGNMENT',
  VILLAGE_SOVEREIGNTY_HUB = 'VILLAGE_SOVEREIGNTY_HUB',
  VILLAGE_SOCIAL_BUDGET = 'VILLAGE_SOCIAL_BUDGET',
  SERVICE_JOURNEY_GUIDE = 'SERVICE_JOURNEY_GUIDE',
  MEMBER_BENEFIT_SIMULATOR = 'MEMBER_BENEFIT_SIMULATOR',
  GOV_PASAR_RAKYAT_BRIDGE = 'GOV_PASAR_RAKYAT_BRIDGE',
  GOV_TENANT_DASHBOARD = 'GOV_TENANT_DASHBOARD'
}

export enum UserRole {
  FOUNDER = 'FOUNDER',
  BOARD = 'BOARD',
  STAFF = 'STAFF',
  MEMBER = 'MEMBER',
  LEADER = 'LEADER',
  AUDITOR = 'AUDITOR',
  GOVERNMENT = 'GOVERNMENT'
}

export interface UserProfile {
  id: string;
  name: string;
  role: UserRole;
  memberId: string;
  balances: {
    principal: number;
    mandatory: number;
    voluntary: number;
  };
  reputationScore: number;
}

export interface ChatMessage {
  role: 'user' | 'model';
  text: string;
}

export interface Transaction {
  id: string;
  type: 'deposit' | 'withdrawal' | 'loan_installment' | 'dividend';
  description: string;
  date: string;
  amount: number;
  status: 'completed' | 'pending' | 'failed';
}