
// Fix: Expanded AppView and UserRole objects to match types.ts for consistent behavior across JS and TS files.
export const AppView = {
  DASHBOARD: 'DASHBOARD',
  REVENUE_CENTER: 'REVENUE_CENTER',
  AI_STRATEGIST: 'AI_STRATEGIST',
  MARKETPLACE: 'MARKETPLACE',
  LOGISTICS: 'LOGISTICS',
  TRANSACTIONS: 'TRANSACTIONS',
  DIGITAL_PASSBOOK: 'DIGITAL_PASSBOOK',
  SHU_DISTRIBUTION: 'SHU_DISTRIBUTION',
  LOAN_SIMULATOR: 'LOAN_SIMULATOR',
  VOUCHING_SYSTEM: 'VOUCHING_SYSTEM',
  LOAN_HISTORY: 'LOAN_HISTORY',
  LOAN_READINESS: 'LOAN_READINESS',
  MEMBER_MARKETPLACE: 'MEMBER_MARKETPLACE',
  SMART_PROCUREMENT: 'SMART_PROCUREMENT',
  MERCHANT_DASHBOARD: 'MERCHANT_DASHBOARD',
  ARISAN_DIGITAL: 'ARISAN_DIGITAL',
  MEMBER_HEALTH_SHIELD: 'MEMBER_HEALTH_SHIELD',
  PERSONAL_GOLD: 'PERSONAL_GOLD',
  PENSION_FUND: 'PENSION_FUND',
  DASKOP_CLAIM: 'DASKOP_CLAIM',
  GLOBAL_COMMAND_CENTER: 'GLOBAL_COMMAND_CENTER',
  STRATEGIC_PROFIT_CALCULATOR: 'STRATEGIC_PROFIT_CALCULATOR',
  ECOSYSTEM_REVENUE: 'ECOSYSTEM_REVENUE',
  DEPLOYMENT_HUB: 'DEPLOYMENT_HUB',
  BILL_PAYMENTS: 'BILL_PAYMENTS',
  SMART_EDUCATION: 'SMART_EDUCATION',
  ACCOUNTING: 'ACCOUNTING',
  AI_CREDIT_COMMITTEE: 'AI_CREDIT_COMMITTEE',
  MEMBER_QRIS: 'MEMBER_QRIS',
  AI_ADVISOR: 'AI_ADVISOR',
  MEMBERSHIP_PROFILE: 'MEMBERSHIP_PROFILE',
  MEMBERSHIP_CERTIFICATE: 'MEMBERSHIP_CERTIFICATE',
  SYSTEM_HEALTH: 'SYSTEM_HEALTH'
};

export const UserRole = {
  FOUNDER: 'FOUNDER',
  BOARD: 'BOARD',
  STAFF: 'STAFF',
  MEMBER: 'MEMBER',
  LEADER: 'LEADER',
  AUDITOR: 'AUDITOR'
};
