
export enum AppView {
  DASHBOARD = 'DASHBOARD',
  TRANSACTIONS = 'TRANSACTIONS',
  SHU_DISTRIBUTION = 'SHU_DISTRIBUTION',
  DIGITAL_PASSBOOK = 'DIGITAL_PASSBOOK',
  LOAN_SIMULATOR = 'LOAN_SIMULATOR',
  VOUCHING_SYSTEM = 'VOUCHING_SYSTEM',
  MEMBER_MARKETPLACE = 'MEMBER_MARKETPLACE',
  MERCHANT_DASHBOARD = 'MERCHANT_DASHBOARD',
  BILL_PAYMENTS = 'BILL_PAYMENTS',
  SMART_EDUCATION = 'SMART_EDUCATION',
  AI_ADVISOR = 'AI_ADVISOR',
  MEMBERSHIP_PROFILE = 'MEMBERSHIP_PROFILE',
  MEMBERSHIP_CERTIFICATE = 'MEMBERSHIP_CERTIFICATE',
  GLOBAL_COMMAND_CENTER = 'GLOBAL_COMMAND_CENTER',
  DEPLOYMENT_HUB = 'DEPLOYMENT_HUB',
  REVENUE_CENTER = 'REVENUE_CENTER',
  NOTIFICATION_CENTER = 'NOTIFICATION_CENTER',
  MONETIZATION_IDEAS = 'MONETIZATION_IDEAS',
  NATIONAL_COMMAND_CENTER = 'NATIONAL_COMMAND_CENTER',
  GOV_SOVEREIGNTY_VAULT = 'GOV_SOVEREIGNTY_VAULT',
  HIERARCHY_VISUALIZER = 'HIERARCHY_VISUALIZER',
  DUTA_TASK_CENTER = 'DUTA_TASK_CENTER',
  MEMBER_TASK_CENTER = 'MEMBER_TASK_CENTER',
  DUTA_PAYROLL_REPORT = 'DUTA_PAYROLL_REPORT',
  MEMBER_QRIS = 'MEMBER_QRIS',
  CASH_WITHDRAWAL = 'CASH_WITHDRAWAL',
  LEGAL_COMPLIANCE = 'LEGAL_COMPLIANCE',
  BYLAWS_EXPLORER = 'BYLAWS_EXPLORER',
  POLICY_ENFORCEMENT = 'POLICY_ENFORCEMENT',
  SYSTEM_HEALTH = 'SYSTEM_HEALTH',
  LOAN_HISTORY = 'LOAN_HISTORY',
  ACCOUNTING = 'ACCOUNTING',
  MEMBER_HEALTH_SHIELD = 'MEMBER_HEALTH_SHIELD',
  BYLAWS_GENERATOR = 'BYLAWS_GENERATOR',
  NATIONAL_LICENSE_GUIDE = 'NATIONAL_LICENSE_GUIDE',
  CAPITAL_ACCUMULATION = 'CAPITAL_ACCUMULATION',
  LEGAL_ROADMAP = 'LEGAL_ROADMAP',
  // New view for the bootstrapping phase
  BOOTSTRAP_CENTER = 'BOOTSTRAP_CENTER'
}

export enum UserRole {
  FOUNDER = 'FOUNDER',
  BOARD = 'BOARD',
  STAFF = 'STAFF',
  MEMBER = 'MEMBER',
  LEADER = 'LEADER',
  LEADER_PROVINCE = 'LEADER_PROVINCE',
  AUDITOR = 'AUDITOR',
  GOVERNMENT = 'GOVERNMENT'
}

export interface UserProfile {
  id: string;
  name: string;
  role: UserRole;
  memberId: string;
  balances: {
    principal: number;
    mandatory: number;
    voluntary: number;
  };
  reputationScore: number;
}

export interface ChatMessage {
  role: 'user' | 'model';
  text: string;
}

export interface Transaction {
  id: string;
  type: 'deposit' | 'withdrawal' | 'loan_installment' | 'dividend';
  description: string;
  date: string;
  amount: number;
  status: 'completed' | 'pending' | 'failed';
}
